# Simple linear algebra with NumPy

In [1]:
import numpy as np

## Some simple practice data
Replace with your own if you feel like it

In [98]:
y = np.array([1, 2, 3, 3, 4])
x = np.array([6, 7, 8, 9, 7])

## The dreaded algebra
\begin{equation}
y = bX
\end{equation}

To solve for $b$, we need to marginalise $X$, and to do that we need to make it a _square_, symmetric matrix. To make it square we multiply both sides of the equation by $X'$

\begin{equation}
X'y = bX'X
\end{equation}

We denote the square matrix as $(X'X)$ and this will have an inverse which we denote as $(X'X)^{-1}$. To marginalise out the square matrix, we need to multiply both sides of the equation by **this** inverse.

\begin{equation}
(X'X)^{-1}X'y = b(X'X)^{-1}X'X
\end{equation}

A square matrix multiplied by its inverse is equal to the identity matrix:
\begin{equation}
I = (X'X)^{-1}X'X
\end{equation}

and a matrix multiplied by the $I$ equals itself.

\begin{equation}
(X'X)^{-1}X'y = bI
\end{equation}

Consequently our unknown $b$ can be represented by:

\begin{equation}
b = X'(X'X)^{-1}y
\end{equation}

**Now let's implement the above using our NumPy library**

Remember that $X$ is expressed as:

\begin{equation}
X = 1 + \sum_{i=1}^{N}x_{i}
\end{equation}

In [99]:
ones = np.ones(x.shape[0])
X_d = np.vstack((ones, x)).T
print(X_d)

[[ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1.  7.]]


In [100]:
X_sq = np.dot(X_d.T, X_d)
print(X_sq)

[[   5.   37.]
 [  37.  279.]]


In [101]:
X_inv = np.linalg.inv(X_sq)
print(X_inv)

[[ 10.73076923  -1.42307692]
 [ -1.42307692   0.19230769]]


In [102]:
Xy = np.dot(X_d.T, y)
print(Xy)

[ 13.  99.]


In [105]:
b = np.dot(Xy, X_inv)
print(b)

[-1.38461538  0.53846154]


In [108]:
print("Our linear solution is:\n\ty = {0:.2f} + {1:.2f}x".format(*tuple(b)))

Our linear solution is:
	y = -1.38 + 0.54x
